INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (1, 'SEO', 'Seoul Dynasty', 'PAC', 4, 0);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (2, 'NYE', 'New York Excelsior', 'ATL', 4, 0);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (3, 'LDN', 'London Spitfire', 'ATL', 4, 0);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (4, 'VAL', 'Los Angeles Valiant', 'PAC', 2, 2);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (5, 'GLA', 'Los Angeles Gladiators', 'PAC', 2, 2);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (6, 'HOU', 'Houston Outlaws', 'ATL', 2, 2);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (7, 'PHI', 'Philadelphia Fusion', 'ATL', 2, 2);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (8, 'BOS', 'Boston Uprising', 'ATL', 1, 3);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (9, 'SFS', 'San Francisco Shock', 'PAC', 2, 2);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (10, 'DAL', 'Dallas Fuel', 'PAC', 0, 4);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (11, 'FLA', 'Florida Mayhem', 'ATL', 1, 3);
INSERT INTO owl.owl_score (team_id, name_abbr, team_name, region, win, lose) VALUES (12, 'SHD', 'Shanghai Dragons', 'PAC', 0, 4);
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (1, 'SEO', 'PAC', 'Seoul Dynasty', '/pic/team/SEO.svg', '#AA8A00', '#000000');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (2, 'NYE', 'ATL', 'New York Excelsior', '/pic/team/NYE.svg', '#0F57EA', '#171C38');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (3, 'LDN', 'ATL', 'London Spitfire', '/pic/team/LDN.svg', '#59CBE8', '#FF8200');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (4, 'VAL', 'PAC', 'Los Angeles Valiant', '/pic/team/VAL.svg', '#000000', '#4A7729');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (5, 'GLA', 'PAC', 'Los Angeles Gladiators', '/pic/team/GLA.svg', '#000000', '#3C1053');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (6, 'HOU', 'ATL', 'Houston Outlaws', '/pic/team/HOU.svg', '#000000', '#97D700');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (7, 'PHI', 'ATL', 'Philadelphia Fusion', '/pic/team/PHI.svg', '#000000', '#FF9E1B');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (8, 'BOS', 'ATL', 'Boston Uprising', '/pic/team/BOS.svg', '#EFDF00', '#174B97');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (9, 'SFS', 'PAC', 'San Francisco Shock', '/pic/team/SFS.svg', '#75787B', '#FC4C02');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (10, 'DAL', 'PAC', 'Dallas Fuel', '/pic/team/DAL.svg', '#0072CE', '#032340');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (11, 'FLA', 'ATL', 'Florida Mayhem', '/pic/team/FLA.svg', '#AF272F', '#FEDB00');
INSERT INTO owl.team_info (team_id, name_abbr, region, team_name, image, accent_color, primary_color) VALUES (12, 'SHD', 'PAC', 'Shanghai Dragons', '/pic/team/SHD.svg', '#000000', '#D22630');