server:
  port: 443
  ssl:
    key-store: #Use your own settings below
    key-store-password:
    key-store-type:
    key-alias:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: #Use your own MySQL Database url
    username: #MySQL UserName
    password: #MySQL Password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
